### ISSUE TITLE
Issues w/ duplicate moduleItems

### ISSUE THREAD

**Issue by mokko** [mokko/MpApi#7]
Issues with multiple nodes. I dont know why I get this. Is it possible that I have the same records multiple times?

Perhaps test it with specially prepared data and the write a select statement that loops only thru distinct records.
```
split/DE-MUS-019118/211835.lido.xml
split/DE-MUS-019118/211836.lido.xml
Error in xsl:result-document/@href on line 20 column 75 of splitLido.xsl:
  XTDE1490  Cannot write more than one result document to the same URI:
  file:/C:/m3/zml2lido/sdata/3Wege/split/DE-MUS-019118/211836.lido.xml
  In template rule with match="/lido:lidoWrap/lido:lido" on line 15 of splitLido.xsl
     invoked by xsl:apply-templates at file:/C:/m3/zml2lido/xsl/splitLido.xsl#12
  In template rule with match="/" on line 11 of splitLido.xsl
Cannot write more than one result document to the same URI: file:/C:/m3/zml2lido/sdata/3Wege/split/DE-MUS-019118/211836.lido.xml
Traceback (most recent call last):
  File "C:\m3\zml2lido\src\lido.py", line 328, in <module>
    getattr(m, args.job)()
  File "C:\m3\zml2lido\src\lido.py", line 142, in smb
    self.splitLido(input=linklido_fn)  # individual records as files
  File "C:\m3\zml2lido\src\lido.py", line 235, in splitLido
    self._saxon(input=input, xsl=xsl["splitLido"], output="o.xml")
  File "C:\m3\zml2lido\src\lido.py", line 303, in _saxon
    subprocess.run(
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command 'java -Xmx1450m -jar C:\m3\SaxonHE10-5J\saxon-he-10.5.jar -s:C:\m3\zml2lido\sdata\3Wege\3Wege20211129-links.onlyPub.lido.xml -xsl:C:\m3\zml2lido\xsl\splitLido.xsl -o:o.xml' returned non-zero exit status 2.
```

**Comment by mokko** [comment]
Todo:Include a tests in split.xsl that checks for duplicates and dies with good error message.

Then avoid problem upstream.

**Comment by mokko** [comment]
Done
